/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminSupportRouteImport } from './routes/_admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/_admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminRolesRouteImport } from './routes/_admin.roles'
import { Route as AdminProfileRouteImport } from './routes/_admin.profile'
import { Route as AdminPlansRouteImport } from './routes/_admin.plans'
import { Route as AdminPermissionsRouteImport } from './routes/_admin.permissions'
import { Route as AdminPaymentsRouteImport } from './routes/_admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminBlogsRouteImport } from './routes/_admin.blogs'
import { Route as AdminBillsRouteImport } from './routes/_admin.bills'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin.audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminAdminsRouteImport } from './routes/_admin.admins'
import { Route as AdminActivityLogsRouteImport } from './routes/_admin.activity-logs'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/activity-logs': typeof AdminActivityLogsRoute
  '/admins': typeof AdminAdminsRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/bills': typeof AdminBillsRoute
  '/blogs': typeof AdminBlogsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/notifications': typeof AdminNotificationsRoute
  '/payments': typeof AdminPaymentsRoute
  '/permissions': typeof AdminPermissionsRoute
  '/plans': typeof AdminPlansRoute
  '/profile': typeof AdminProfileRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/activity-logs': typeof AdminActivityLogsRoute
  '/admins': typeof AdminAdminsRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/bills': typeof AdminBillsRoute
  '/blogs': typeof AdminBlogsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/notifications': typeof AdminNotificationsRoute
  '/payments': typeof AdminPaymentsRoute
  '/permissions': typeof AdminPermissionsRoute
  '/plans': typeof AdminPlansRoute
  '/profile': typeof AdminProfileRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRoute
  '/subscriptions': typeof AdminSubscriptionsRoute
  '/support': typeof AdminSupportRoute
  '/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/activity-logs': typeof AdminActivityLogsRoute
  '/_admin/admins': typeof AdminAdminsRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/bills': typeof AdminBillsRoute
  '/_admin/blogs': typeof AdminBlogsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/payments': typeof AdminPaymentsRoute
  '/_admin/permissions': typeof AdminPermissionsRoute
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_admin/roles': typeof AdminRolesRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/subscriptions': typeof AdminSubscriptionsRoute
  '/_admin/support': typeof AdminSupportRoute
  '/_admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/activity-logs'
    | '/admins'
    | '/analytics'
    | '/audit-logs'
    | '/bills'
    | '/blogs'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/permissions'
    | '/plans'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/activity-logs'
    | '/admins'
    | '/analytics'
    | '/audit-logs'
    | '/bills'
    | '/blogs'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/permissions'
    | '/plans'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/unauthorized'
    | '/_admin/activity-logs'
    | '/_admin/admins'
    | '/_admin/analytics'
    | '/_admin/audit-logs'
    | '/_admin/bills'
    | '/_admin/blogs'
    | '/_admin/dashboard'
    | '/_admin/notifications'
    | '/_admin/payments'
    | '/_admin/permissions'
    | '/_admin/plans'
    | '/_admin/profile'
    | '/_admin/roles'
    | '/_admin/settings'
    | '/_admin/subscriptions'
    | '/_admin/support'
    | '/_admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support': {
      id: '/_admin/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/subscriptions': {
      id: '/_admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles': {
      id: '/_admin/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/permissions': {
      id: '/_admin/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blogs': {
      id: '/_admin/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bills': {
      id: '/_admin/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admins': {
      id: '/_admin/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/activity-logs': {
      id: '/_admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBillsRoute: typeof AdminBillsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBillsRoute: AdminBillsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
